### PR TITLE
Adds Noscript-Tags to the tag-blacklist

### PR DESCRIPTION
**Pull request by Schleuse**
I've been using [Lazysizes with the noscript-Pattern](https://github.com/aFarkas/lazysizes#the-noscript-pattern) for a while and wanted to add smartquotes to my websites as well.
But when I enable it all the tag-quotes in the `noscript`-tags are getting replaced by the fancy ones and the images wont load :smile: obviously.

So, this PR add's the `noscript-tag to the element blacklist.

### CODE REVIEW

**Comment by kellym** [comment]
Sorry for the very long delay on this. A new issue mentioned a similar issue. It looks like to me that there's a problem with the logic in handling `noscript` tags. They shouldn't be excluded, but they're not being treated correctly.

**Comment by anthonydillon** [comment]
I can't see why it would matter if noscript content was excluded. The content can only be visible if simplequotes cannot affect it.

**Comment by kellym** [comment]
Ha, that's a good point. Someone else is actually using the `noscript` content with JavaScript enabled. It does make sense to exclude it, you're right.

**Comment by anthonydillon** [comment]
Should probably ignore the `dist` directory?

**Comment by Schleuse** [comment]
I've removed the `dist` directory from the PR :ok_hand:

**Comment by anthonydillon** [comment]
@kellym is this PR ok to land and be released so I can test it?

**Comment by pmahnke** [comment]
@kellym is there a reason to hold this up?  We cannot use it until you merge and release it.

**Comment by kellym** [comment]
Looks great to me. Sorry for the delays!

**Comment by kellym** [comment]
Published 2.3.2 with the changes. Thanks and apologies again!

**Comment by pmahnke** [comment]
@kellym and @Schleuse thank you!

**Pull request merged**
